version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - npm install -g aws-cdk
  build:
    commands:
      - cdk deploy --app 'python app.py' TestStack
post_build:
  commands:
    - echo "Test Stage Deployed"
artifacts:
  files: '**/*'